name: React.js CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the React application
      run: npm run build

    - name: Verify build directory
      run: ls -al dist

    - name: Prepare server for deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          rm -rf /home/jaja/test-cd-react/*

    - name: Copy build files to server
      run: |
        sshpass -p ${{ secrets.SSH_PASS }} scp -o StrictHostKeyChecking=no -r dist/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/jaja/test-cd-react/
